; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:nm-cyd-c5]
board = esp32-c5-devkitc-1
board_build.partitions = custom_8Mb.csv
build_src_filter =${env.build_src_filter} +<../boards/nm-cyd-c5>
build_flags =
	${env.build_flags}
	-Iboards/nm-cyd-c5
	-DDEVICE_NAME='"ESP32-C5"'
	-DNM_CYD_ESP32C5=1
	-DBOARD_HAS_PSRAM=1
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DARDUINO_USB_MODE=1
	-DCORE_DEBUG_LEVEL=1
	-DHAS_TOUCH=1
	-DROTATION=3

	-DGPS_SERIAL_TX=5
	-DGPS_SERIAL_RX=4
	; grove pins
	; defaults from https://github.com/espressif/arduino-esp32/blob/master/variants/esp32s3/pins_arduino.h
	-DGROVE_SDA=9  ; default IR/RF RX pin
	-DGROVE_SCL=8  ; default IR/RF TX pin
	;-DALLOW_ALL_GPIO_FOR_IR_RF=1 ; Set this option to make use of all GPIOs, from 1 to 44 to be chosen, except TFT and SD pins

	; ir led pin
	-DIR_TX_PINS='{{"Pin 9", 9}, {"Pin 8", 8}}'
	-DIR_RX_PINS='{{"Pin 9", 9}, {"Pin 8", 8}}'
	-DLED_ON=HIGH
	-DLED_OFF=LOW

	;Radio Frequency (one pin modules) pin setting
	-DRF_TX_PINS='{{"Pin 9", 9}, {"Pin 8", 8}}'
	-DRF_RX_PINS='{{"Pin 9", 9}, {"Pin 8", 8}}'

	; text sizes
	-DFP=1
	-DFM=2
	-DFG=3
	; ui control buttons
	;-DSEL_BTN=1
	;-DUP_BTN=2  ; also work as ESC
	;-DDW_BTN=3  ; also work as NEXT
	-DBTN_ALIAS='"OK"'

	;FM Radio
	-DFM_SI4713=1 ;Uncomment to activate FM Radio using Adafruit Si4713


