[env:reaper]
board = reaper
board_build.partitions = custom_16Mb.csv
build_src_filter =${env.build_src_filter} +<../boards/reaper>
build_flags =
	${env.build_flags}
	-Iboards/reaper
	-Os
	-DARDUINO_USB_MODE=1
	-DBUZZ_PIN=10
    -D USE_HSPI_PORT=1
    -DDEVICE_NAME='"reaper board"'

	-DCORE_DEBUG_LEVEL=0

	;Infrared Led default pin and state
	-DIR_TX_PINS='{{"GPIO 2", 2}, {"GPIO 4", 4}, {"GPIO 5", 5}, {"GPIO 42", 42}}'
	-DIR_RX_PINS='{{"GPIO 1", 1}, {"GPIO 4", 4}, {"GPIO 5", 5}, {"GPIO 42", 42}}'
    -DRF_TX_PINS='{{"GPIO 4", 4}, {"GPIO 5", 5}, {"GPIO 42", 42}}'
	-DRF_RX_PINS='{{"GPIO 4", 4}, {"GPIO 5", 5}, {"GPIO 42", 42}}'


lib_deps =
	${env.lib_deps}
	lewisxhe/XPowersLib @0.3.2

