; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:m5stack-dinmeter]
board = m5stack-dinmeter
board_build.partitions = custom_8Mb.csv
build_src_filter =${env.build_src_filter} +<../boards/m5stack-dinmeter>
build_flags =
	${env.build_flags}
	-Iboards/m5stack-dinmeter
	-D CORE_DEBUG_LEVEL=1

	-D DEVICE_NAME='"M5DinMeter"'
	-D HAS_ENCODER=1
	-D ROTATION=3

	-D ENCODER_INA=41
	-D ENCODER_INB=40
	-D ENCODER_KEY=42

	-D BTN_ALIAS='"SEL"'
	-D LED=-1
	-D LED_ON=HIGH
	; Using M5GFX driver
	-D HAS_SCREEN=1
	-D ROTATION=3

	-D USE_M5GFX=1
	-D TFT_WIDTH=135
	-D TFT_HEIGHT=240

	-D SPI_SCK_PIN=15
	-D SPI_MOSI_PIN=1
	-D SPI_MISO_PIN=2
	-D SPI_SS_PIN=13

	;Default I2C port
	-D GROVE_SDA=1
	-D GROVE_SCL=2
	-D SYS_I2C_SDA=11
	-D SYS_I2C_SCL=12

	;Features Enabled
	;-DLITE_VERSION=1 ;limits some features to save space for M5Launcher Compatibility
	;-DMIC_SPM1423=1 ;Applicable for SPM1423 device
	;FM Radio
	-D FM_SI4713=1
	-D FM_RSTPIN=-1

	;Sound options
	-D BUZZ_PIN=3

	;Can run USB as HID
	-D USB_as_HID=1 ;uncomment to enable

	;-DALLOW_ALL_GPIO_FOR_IR_RF=1 ; Set this option to make use of all GPIOs, from 1 to 44 to be chosen, except TFT and SD pins
	;Infrared Led default pin and state
	-D IR_TX_PINS='{{"G1",1},{"G2",2},{"G13",13},{"G15",15}}'
	-D IR_RX_PINS='{{"G1",1},{"G2",2},{"G13",13},{"G15",15}}'
	-D TXLED=1
	-D RXLED=2
	-D LED_ON=HIGH
	-D LED_OFF=LOW

	;Radio Frequency (one pin modules) pin setting
	-D RF_TX_PINS='{{"G1",1},{"G2",2},{"G13",13},{"G15",15}}'
	-D RF_RX_PINS='{{"G1",1},{"G2",2},{"G13",13},{"G15",15}}'

	; -DUSE_CC1101_VIA_SPI # deprecated
	-DCC1101_GDO0_PIN=SPI_SS_PIN
	-DCC1101_SS_PIN=-1
	-DCC1101_MOSI_PIN=SPI_MOSI_PIN
	-DCC1101_SCK_PIN=SPI_SCK_PIN
	-DCC1101_MISO_PIN=SPI_MISO_PIN

	; -DUSE_NRF24_VIA_SPI # deprecated
	-DNRF24_CE_PIN=-1
	-DNRF24_SS_PIN=SPI_SS_PIN
	-DNRF24_MOSI_PIN=SPI_MOSI_PIN
	-DNRF24_SCK_PIN=SPI_SCK_PIN
	-DNRF24_MISO_PIN=SPI_MISO_PIN

	; -DUSE_W5500_VIA_SPI # deprecated
	-DW5500_SS_PIN=-1
	-DW5500_MOSI_PIN=SPI_MOSI_PIN
	-DW5500_SCK_PIN=SPI_SCK_PIN
	-DW5500_MISO_PIN=SPI_MISO_PIN
	-DW5500_INT_PIN=-1

	;Lora setup pins
	-DLORA_SCK=SPI_SCK_PIN
	-DLORA_MISO=SPI_MISO_PIN
	-DLORA_MOSI=SPI_MOSI_PIN
	-DLORA_CS=-1
	-DLORA_RST=-1
	-DLORA_DIO0=-1

	;SD Card Setup pins
	-D SDCARD_CS=SPI_SS_PIN
	-D SDCARD_SCK=SPI_SCK_PIN
	-D SDCARD_MISO=SPI_MISO_PIN
	-D SDCARD_MOSI=SPI_MOSI_PIN

	; SERIAL (GPS) dedicated pins
	-D SERIAL_TX=13
	-D SERIAL_RX=15
	-D GPS_SERIAL_TX=13
	-D GPS_SERIAL_RX=15

lib_deps =
	${env.lib_deps}
	m5stack/M5Unified

lib_ignore =
	TFT_eSPI


